"""初始化数据库表结构

Revision ID: 21345f65c7bf
Revises:
Create Date: 2025-12-07 13:28:19.076380

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision: str = '21345f65c7bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库结构。"""
    # ### commands auto generated by Alembic - please adjust! ###
    # 创建tenants表
    op.create_table('tenants',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('corp_id', sa.String(length=64), nullable=False, comment='企业ID'),
        sa.Column('corp_name', sa.String(length=128), nullable=True, comment='企业名称'),
        sa.Column('permanent_code', sa.String(length=512), nullable=True, comment='永久授权码'),
        sa.Column('auth_code', sa.String(length=512), nullable=True, comment='临时授权码'),
        sa.Column('auth_time', sa.DateTime(), nullable=True, comment='授权时间'),
        sa.Column('is_active', sa.Boolean(), nullable=True, default=True, comment='是否激活'),
        sa.Column('is_authorized', sa.Boolean(), nullable=True, default=False, comment='是否已授权'),
        sa.Column('callback_url', sa.String(length=512), nullable=True, comment='回调URL'),
        sa.Column('callback_token', sa.String(length=128), nullable=True, comment='回调Token'),
        sa.Column('callback_aes_key', sa.String(length=128), nullable=True, comment='回调加密密钥'),
        sa.Column('contact_name', sa.String(length=64), nullable=True, comment='联系人姓名'),
        sa.Column('contact_phone', sa.String(length=32), nullable=True, comment='联系人电话'),
        sa.Column('contact_email', sa.String(length=128), nullable=True, comment='联系人邮箱'),
        sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
        sa.Column('created_at', sa.DateTime(), nullable=True, default=datetime.utcnow, comment='创建时间'),
        sa.Column('updated_at', sa.DateTime(), nullable=True, default=datetime.utcnow, onupdate=datetime.utcnow, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('corp_id'),
        mysql_charset='utf8mb4',
        mysql_collate='utf8mb4_unicode_ci',
        comment='租户表 - 存储授权企业的信息'
    )
    op.create_index('ix_tenants_corp_id', 'tenants', ['corp_id'], unique=False)

    # 插入默认租户数据
    op.execute("""
        INSERT INTO tenants (corp_id, corp_name, contact_name, contact_phone, contact_email,
                           permanent_code, is_authorized, callback_url, callback_token,
                           callback_aes_key, created_at, updated_at)
        VALUES ('ww4c543662478cf668', '测试企业', '系统管理员', '400-123-4567',
                'admin@example.com', 'test_permanent_code', false,
                'https://wxkf.shoudu888.com/callback/customer-service', 'KLNsSkfx9',
                'wOoBhDpcsBEC1YlQrD768hPFufWAIkWXS7y1bsWAFtK', NOW(), NOW())
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库结构。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tenants_corp_id', table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###