apiVersion: v1
kind: Service
metadata:
  name: wxkf-staging-service
  namespace: wxkf-staging
  labels:
    app: wxkf-staging
spec:
  type: ClusterIP
  selector:
    app: wxkf-staging
  ports:
  - name: http
    port: 80
    targetPort: 8083
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: wxkf-staging-headless
  namespace: wxkf-staging
  labels:
    app: wxkf-staging
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: wxkf-staging
  ports:
  - name: http
    port: 8083
    targetPort: 8083
    protocol: TCP